[package]
name = "wslgit"
version = "1.0.0"
authors = ["Andreas Riffnaller-Schiefer <andreas.schiefer@gmail.com>"]
license = "MIT"

[dependencies]
regex = "1"
lazy_static = "1.4"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"
